//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accurals
    {
        public int id { get; set; }
        public int userID { get; set; }
        public Nullable<decimal> sum { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual users users { get; set; }
    }
}
